name: UpdateChecker
version: '1.0'
main: me.acclashcorporation.updatechecker.UpdateChecker
api-version: 1.18
authors: [ Anston_Sorensen ]
description: A plugin that checks the server software version and installs a newer version if needed.